version: "3"

services:
  db:
    image: m.docker-registry.ir/postgres:12-alpine3.15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saku-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=saku1234
    ports:
      - "15432:5432"

  redis:
    image: m.docker-registry.ir/redis:7.0.1-alpine
    command: redis-server
    ports:
      - "16379:6379"

  web:
    build: .
    tty: true
    command: /bin/sh -c "cd saku && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    restart: always
    build:
      context: .
    command: /bin/sh -c "cd saku && celery -A saku worker -l info"
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_NAME=saku-db
      - DB_USER=postgres
      - DB_PASS=saku1234
    depends_on:
      - db
      - redis
      - web
