version: "3"

services:
  db:
    image: m.docker-registry.ir/postgres:12-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saku-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=saku1234
    ports:
      - "5432:5432"

  web:
    image: "ghcr.io/mehdi-mostafavi/saku:${TAG}"
    command: /bin/sh -c "cd saku && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8888"
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data: