version: "3"

services:
  db:
    image: m.docker-registry.ir/postgres:12-alpine3.15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saku-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=saku1234
    ports:
      - "15432:5432"

  redis:
    image: m.docker-registry.ir/redis:7.0.2-alpine
    command: redis-server
    ports:
      - "26379:6379"

  web:
    build: .
    tty: true
    command: /bin/sh -c "cd saku && python manage.py test"
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis

