version: "3.3"

services:
  db:
    image: m.docker-registry.ir/postgres:12-alpine3.15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saku-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=saku1234
    ports:
      - "15432:5432"

  web:
    build: .
    tty: true
    command: /bin/sh -c "cd saku && python manage.py test"
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db
      - minio

  minio:
    image: m.docker-registry.ir/minio/minio:edge
    command: minio server ./data --address '0.0.0.0:9008' --console-address "0.0.0.0:9007"
    ports:
      - "9007:9007"
      - "9008:9008"
    volumes:
      - ./storage/minio:/data
