name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: build docker
      run: |
        docker build . -t ghcr.io/mehdi-mostafavi/saku:${{ github.sha }}

    - name: push
      run: |
        docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.PAT }} ghcr.io
        docker push ghcr.io/mehdi-mostafavi/saku:${{ github.sha }}


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Run Tests
      run: |
        docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.PAT }} ghcr.io
        docker pull ghcr.io/mehdi-mostafavi/saku:${{ github.sha }}
        docker-compose -f docker-compose.test.yml run web

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH }}

      - name: Deploy
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@188.121.110.151 "cd Saku-Backend && export TAG=${{ github.sha }} && git checkout Feature/Create_docker_image && git fetch --all && git reset --hard origin/Feature/Create_docker_image && docker-compose down && docker-compose -f docker-compose.deploy.yml up -d"
